### ISSUE TITLE
rdfs:Property is generated instead of rdf:Property

### ISSUE THREAD

**Issue by aamedina** [w3c/yml2vocab#16]
When RDF properties are generated the class rdfs:Property is used, but that term doesn't exist in the RDF schema namespace. I believe this is a typo for rdf:Property.

Source: https://www.w3.org/TR/rdf12-schema/#ch_property

I found this when generating a database schema importing the security vocabulary which throws an error when a term isn't resolved: https://github.com/w3c/vc-data-integrity/tree/main/vocab/security

**Comment by iherman** [comment]
Thank you, @aamedina, this was indeed a bug.

I have created a PR (see #17) for this. Note, however, that it may take a while for the results to propagate to the security vocabulary itself: it will need to get through PR on that repository, and the WG has a very big backlog of things to do. Sorry about that.

**Comment by aamedina** [comment]
No problem, thanks for addressing this! Looking forward to the official recommendation for the data security vocabularies & more! :)
